/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Gerbong;
import Controller.Kereta;
import Model.Penumpang;
import Model.Tiket;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anggi
 */
public class CariTiketPanel extends javax.swing.JPanel {

    ArrayList<Kereta> keretas = DataHolder.keretas;
    ArrayList<Tiket> tikets = DataHolder.tikets;
    ArrayList<String> keretaComboDatas = new ArrayList<String>();
    String[] infoGerbongComboDatas;
    Tiket currentTiket;
    
    /**
     * Creates new form CariTiketPanel
     */
    public CariTiketPanel() {
        for (Kereta kereta : keretas) {
            keretaComboDatas.add(kereta.getNama());
        }
        
        initComponents();
        
        displayDataKereta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        keretaCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        kodeTiketTextField = new javax.swing.JTextField();
        cariTiketButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        infoNamaKeretaTextField = new javax.swing.JTextField();
        infoStasiunAsalTextField = new javax.swing.JTextField();
        infoStasiunTujuanTextField = new javax.swing.JTextField();
        infoJadwalSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        infoKTPTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        infoNamaTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        infoAlamatArea = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        infoKodeTiketTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        infoGerbongCombo = new javax.swing.JComboBox();
        printUlangButton = new javax.swing.JButton();
        ubahTiketButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        infoHargaTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        infoTanggalPembelianTextField = new javax.swing.JTextField();
        batalkanTiketButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(910, 428));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kode Tiket"));

        jLabel1.setText("Pilih Kereta");

        keretaCombo.setModel(new javax.swing.DefaultComboBoxModel(keretaComboDatas.toArray()));

        jLabel2.setText("Kode Tiket");

        cariTiketButton.setText("Cari TIket");
        cariTiketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariTiketButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cariTiketButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(keretaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kodeTiketTextField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(keretaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kodeTiketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(cariTiketButton)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Kereta"));

        infoNamaKeretaTextField.setEditable(false);

        infoStasiunAsalTextField.setEditable(false);

        infoStasiunTujuanTextField.setEditable(false);

        infoJadwalSpinner.setModel(new javax.swing.SpinnerDateModel());

        jLabel7.setText("Jadwal");

        jLabel5.setText("Stasiun Tujuan");

        jLabel3.setText("Stasiun Asal");

        jLabel4.setText("Nama Kereta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(infoStasiunTujuanTextField)
                    .addComponent(infoStasiunAsalTextField)
                    .addComponent(infoNamaKeretaTextField)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(infoJadwalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 179, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(infoNamaKeretaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(infoStasiunAsalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(infoStasiunTujuanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(infoJadwalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 75, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Tiket"));

        jLabel8.setText("No KTP");

        infoKTPTextField.setEditable(false);

        jLabel9.setText("Nama");

        infoNamaTextField.setEditable(false);

        infoAlamatArea.setEditable(false);
        infoAlamatArea.setColumns(20);
        infoAlamatArea.setRows(5);
        jScrollPane2.setViewportView(infoAlamatArea);

        jLabel10.setText("Alamat");

        jLabel11.setText("Kode Tiket");

        infoKodeTiketTextField.setEditable(false);

        jLabel6.setText("Gerbong");

        printUlangButton.setText("Print Ulang");
        printUlangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printUlangButtonActionPerformed(evt);
            }
        });

        ubahTiketButton.setText("Ubah");
        ubahTiketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahTiketButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("Harga");

        infoHargaTextField.setEditable(false);

        jLabel13.setText("Tanggal Pembelian");

        infoTanggalPembelianTextField.setEditable(false);

        batalkanTiketButton.setText("Batalkan Tiket");
        batalkanTiketButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalkanTiketButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 81, Short.MAX_VALUE)
                        .addComponent(batalkanTiketButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ubahTiketButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printUlangButton))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(infoKTPTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(infoNamaTextField)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(infoKodeTiketTextField)
                            .addComponent(infoHargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoGerbongCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoTanggalPembelianTextField)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(infoGerbongCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(infoKTPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(infoNamaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(infoKodeTiketTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(infoHargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(infoTanggalPembelianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printUlangButton)
                    .addComponent(ubahTiketButton)
                    .addComponent(batalkanTiketButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cariTiketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariTiketButtonActionPerformed
        ArrayList<Tiket> keretaTikets = new ArrayList<Tiket>();
        for(Tiket tiket : tikets) {
            if (tiket.getKereta().equals(keretas.get(keretaCombo.getSelectedIndex()))) {
                keretaTikets.add(tiket);
            }
        }
        
        Tiket found = null;
        for(Tiket tiket : keretaTikets) {
            if (tiket.getNoKursi().equalsIgnoreCase(kodeTiketTextField.getText())) {
                found = tiket;
                break;
            }
        }
        
        if (found != null) {
            currentTiket = found;
            displatDataTiket();
        } else {
            JOptionPane.showMessageDialog(null, "Tiket dengan kode tiket " + kodeTiketTextField.getText() + " tidak ditemukan.", "Not Found", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_cariTiketButtonActionPerformed

    private void ubahTiketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahTiketButtonActionPerformed
        if (ubahTiketButton.getText().equalsIgnoreCase("simpan")) {
            currentTiket.getPenumpang().setNoKTP(infoKTPTextField.getText());
            currentTiket.getPenumpang().setNama(infoNamaTextField.getText());
            currentTiket.getPenumpang().setAlamat(infoAlamatArea.getText());
            
            ubahTiketButton.setText("Ubah");
            setEditableInfo(false);
        } else {
            ubahTiketButton.setText("Simpan");
            setEditableInfo(true);
        }
    }//GEN-LAST:event_ubahTiketButtonActionPerformed

    private void printUlangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printUlangButtonActionPerformed
        if (currentTiket != null) {
            System.out.println(currentTiket);
        }
    }//GEN-LAST:event_printUlangButtonActionPerformed

    private void batalkanTiketButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalkanTiketButtonActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(null, "Apakah anda yakin akan membatalkan tiket ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (dialogResult == JOptionPane.YES_OPTION) {
            currentTiket.getGerbong().getPenumpangs().remove(currentTiket.getPenumpang());
            tikets.remove(currentTiket);
            currentTiket = null;
            
            infoKTPTextField.setText("");
            infoNamaTextField.setText("");
            infoAlamatArea.setText("");
            infoKodeTiketTextField.setText("");
            infoHargaTextField.setText("");
            infoTanggalPembelianTextField.setText("");
        }
    }//GEN-LAST:event_batalkanTiketButtonActionPerformed

    private void setEditableInfo(boolean b) {
        infoHargaTextField.setEditable(b);
        infoKTPTextField.setEditable(b);
        infoNamaTextField.setEditable(b);
        infoAlamatArea.setEditable(b);
    }
    
    private void displatDataTiket() {
        for (int i = 0; i < infoGerbongComboDatas.length; i++) {
            if (currentTiket.getGerbong().getKodeGerbong().equals(infoGerbongComboDatas[i])) {
                infoGerbongCombo.setSelectedIndex(i);
            }
        }
        
        infoKTPTextField.setText(currentTiket.getPenumpang().getNoKTP());
        infoNamaTextField.setText(currentTiket.getPenumpang().getNama());
        infoAlamatArea.setText(currentTiket.getPenumpang().getAlamat());
        infoKodeTiketTextField.setText(currentTiket.getNoKursi());
        infoHargaTextField.setText(String.valueOf(currentTiket.getGerbong().getHarga()));
        infoTanggalPembelianTextField.setText(String.valueOf(currentTiket.getTanggal()));
    }
    
    private void displayDataKereta() {
        Kereta kereta = keretas.get(keretaCombo.getSelectedIndex());
        
        infoGerbongComboDatas = new String[kereta.getGerbongs().size()];
        int i = 0;
        for (Gerbong gerbong : kereta.getGerbongs()) {
            infoGerbongComboDatas[i++] = gerbong.getKodeGerbong();
        }
        
        infoGerbongCombo.setModel(new DefaultComboBoxModel(infoGerbongComboDatas));
        
        infoNamaKeretaTextField.setText(kereta.getNama());
        infoStasiunAsalTextField.setText(kereta.getRute().getAsal().getNama() + ", " + kereta.getRute().getAsal().getDaerah());
        infoStasiunTujuanTextField.setText(kereta.getRute().getTujuan().getNama() + ", " + kereta.getRute().getTujuan().getDaerah());
        infoJadwalSpinner.setValue(kereta.getJadwal());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalkanTiketButton;
    private javax.swing.JButton cariTiketButton;
    private javax.swing.JTextArea infoAlamatArea;
    private javax.swing.JComboBox infoGerbongCombo;
    private javax.swing.JTextField infoHargaTextField;
    private javax.swing.JSpinner infoJadwalSpinner;
    private javax.swing.JTextField infoKTPTextField;
    private javax.swing.JTextField infoKodeTiketTextField;
    private javax.swing.JTextField infoNamaKeretaTextField;
    private javax.swing.JTextField infoNamaTextField;
    private javax.swing.JTextField infoStasiunAsalTextField;
    private javax.swing.JTextField infoStasiunTujuanTextField;
    private javax.swing.JTextField infoTanggalPembelianTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox keretaCombo;
    private javax.swing.JTextField kodeTiketTextField;
    private javax.swing.JButton printUlangButton;
    private javax.swing.JButton ubahTiketButton;
    // End of variables declaration//GEN-END:variables
}
