/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this te
    @Override
    public void setSelectedItem(Object anItem) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Object getSelectedItem() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getSize() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public E getElementAt(int index) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void addListDataListener(ListDataListener l) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void removeListDataListener(ListDataListener l) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
mplate file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Gerbong;
import Controller.Kereta;
import Model.Penumpang;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anggi
 */
public class CekKeretaPanel extends javax.swing.JPanel {
    
    ArrayList<Kereta> keretas = DataHolder.keretas;
    ArrayList<String> keretaComboDatas = new ArrayList<String>();

    /**
     * Creates new form cekKeretaPanel
     */
    public CekKeretaPanel() {
        for (Kereta kereta : keretas) {
            keretaComboDatas.add(kereta.getNama());
        }
        
        initComponents();
        
        displayDataKereta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        gerbongsTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        infoStasiunAsalTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        infoStasiunTujuanTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        infoJadwalSpinner = new javax.swing.JSpinner();
        keretaCombo = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        penumpangsTable = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(910, 428));
        setSize(new java.awt.Dimension(910, 428));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Info Kereta"));
        jPanel3.setToolTipText("");

        gerbongsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        gerbongsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gerbongsTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(gerbongsTable);

        jLabel2.setText("Nama Kereta");

        jLabel3.setText("Stasiun Asal");

        infoStasiunAsalTextField.setEditable(false);

        jLabel5.setText("Stasiun Tujuan");

        infoStasiunTujuanTextField.setEditable(false);

        jLabel6.setText("Info Gerbong");

        jLabel7.setText("Jadwal");

        infoJadwalSpinner.setModel(new javax.swing.SpinnerDateModel());

        keretaCombo.setModel(new javax.swing.DefaultComboBoxModel(keretaComboDatas.toArray()));
        keretaCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keretaComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(infoJadwalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 204, Short.MAX_VALUE))
                            .addComponent(keretaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(infoStasiunAsalTextField)
                            .addComponent(infoStasiunTujuanTextField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(keretaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(infoStasiunAsalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(infoStasiunTujuanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(infoJadwalSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detail Penumpang Gerbong"));

        penumpangsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "No KTP", "Nama", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(penumpangsTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void keretaComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keretaComboActionPerformed
        displayDataKereta();
    }//GEN-LAST:event_keretaComboActionPerformed

    private void gerbongsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gerbongsTableMouseClicked
        Kereta kereta = keretas.get(keretaCombo.getSelectedIndex());
        Gerbong gerbong = kereta.getGerbongs().get(gerbongsTable.getSelectedRow());
        String[] penumpangsTableTitles = {"No", "No KTP", "Nama", "Alamat"};
        String[][] penumpangsTableDatas = new String[gerbong.getPenumpangs().size()][penumpangsTableTitles.length];

        int i = 0;
        for (Penumpang penumpang : gerbong.getPenumpangs()) {
            penumpangsTableDatas[i][1] = penumpang.getNoKTP();
            penumpangsTableDatas[i][2] = penumpang.getNama();
            penumpangsTableDatas[i][3] = penumpang.getAlamat();
            penumpangsTableDatas[i][0] = String.valueOf(++i);
        }

        penumpangsTable.setModel(new DefaultTableModel(penumpangsTableDatas, penumpangsTableTitles));
    }//GEN-LAST:event_gerbongsTableMouseClicked

    public void reload() {
        displayDataKereta();
    }
    
    private void displayDataKereta() {
        Kereta kereta = keretas.get(keretaCombo.getSelectedIndex());
        String[] gerbongsTableTitles = {"No", "Kode Gerbong", "Harga", "Jumlah Kursi", "Terpesan"};
        String[][] gerbongsTableDatas = new String[kereta.getGerbongs().size()][gerbongsTableTitles.length];
        
        int i = 0;
        for (Gerbong gerbong : kereta.getGerbongs()) {
            gerbongsTableDatas[i][1] = gerbong.getKodeGerbong();
            gerbongsTableDatas[i][2] = String.valueOf(gerbong.getHarga());
            gerbongsTableDatas[i][3] = String.valueOf(gerbong.getJumlahKursi());
            gerbongsTableDatas[i][4] = String.valueOf(gerbong.getPenumpangs().size());
            gerbongsTableDatas[i][0] = String.valueOf(++i);
        }
        
        gerbongsTable.setModel(new DefaultTableModel(gerbongsTableDatas, gerbongsTableTitles));
        infoStasiunAsalTextField.setText(kereta.getRute().getAsal().getNama() + ", " + kereta.getRute().getAsal().getDaerah());
        infoStasiunTujuanTextField.setText(kereta.getRute().getTujuan().getNama() + ", " + kereta.getRute().getTujuan().getDaerah());
        infoJadwalSpinner.setValue(kereta.getJadwal());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable gerbongsTable;
    private javax.swing.JSpinner infoJadwalSpinner;
    private javax.swing.JTextField infoStasiunAsalTextField;
    private javax.swing.JTextField infoStasiunTujuanTextField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox keretaCombo;
    private javax.swing.JTable penumpangsTable;
    // End of variables declaration//GEN-END:variables
}
